version: '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: postgres-instantchat
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: instantchat
    ports:
      - "5432:5432"
    volumes:
      - instantchat:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: redis-instantchat
    ports:
      - "6379:6379"
    command: [ "redis-server"]

volumes:
  instantchat: