services:
  postgres:
    image: postgres:17.4
    container_name: postgres-instantchat
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: instantchat
    ports:
      - "5432:5432"
    volumes:
      - instantchat:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: redis-instantchat
    ports:
      - "6379:6379"
    command: ["redis-server"]

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instantchat-server
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: instantchat
      DB_PASSWORD: 123
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    restart: unless-stopped

  client:
    build:
      context: ../InstantChat-Client
      dockerfile: Dockerfile
    container_name: instantchat-client
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  instantchat:
networks:
  instantchat-network:
    driver: bridge